### ISSUE TITLE
DJ's Bug Report Findings

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#10]
Hello! This is DJ Panda. So I have been having issues with getting legal shiny legends. Usually the end up in some sort of error.

Manaphy @ Waterium Z
Shiny: Yes
Ability: Hydration
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
- Tail Glow
- Surf
- Psychic
- Rain Dance

This one gives me a fixed mystery gift nature. I thought there was a event that could be shiny with no nature limit.

Mew @ Leftovers
Ability: Synchronize
Shiny: Yes
EVs: 240 HP / 156 Def / 112 Spe
Timid Nature
- Ice Beam
- Will-O-Wisp
- Soft-Boiled
- Defog

This one gets it legally but ignores making it shiny. I am able to make it shiny by manually doing it, but that defeats the purpose of the auto mod. ;)

Doritoes (Zapdos) @ Choice Scarf  
Ability: Pressure  
Shiny: Yes  
EVs: 252 SpA / 252 Spe  
Modest Nature  
IVs: 0 Atk  
- Defog  
- Hidden Power [Ice]  
- Volt Switch  
- Air Cutter

Even more interesting, it manages to legally create the shiny but fails to do a proper HP. This seems to happen with all shiny legends in gen 4. (The program makes pretty much all the IVs 0 except for one.)

Finally,

Virsachi (Jirachi) @ King's Rock  
Ability: Serene Grace  
EVs: 104 HP / 252 Atk / 36 Def / 32 SpD / 84 Spe  
Adamant Nature  
- Iron Head  
- Ice Punch  
- Stealth Rock  
- Drain Punch

Any Jirachi request I have done so far ends up shiny even when the set says it doesn't. I don't know why this happens unless all the legal possible Jirachi sets can only be shiny.

Appreciate the help!
-DJ Panda

**Comment by DJPanda065** [comment]
Another weird bug.

Here'sBrucey (Sharpedo-Mega) (M) @ Sharpedonite
Ability: Speed Boost
Shiny: Yes
EVs: 252 Atk / 4 SpD / 252 Spe
Adamant Nature
- Waterfall
- Crunch
- Psychic Fangs
- Protect

The set displays normally when it asks if this is the set you want to import but then it gives Rough Skin as the ability instead of Speed Boost.

**Comment by Pierrounator** [comment]
For the Sharpedo one it's due to the `-Mega` part. I already had this bug and if you remove it, it works fine.
_if it can help to resolve this bug..._

**Comment by DJPanda065** [comment]
Basculin-Blue-Striped (F) @ Life Orb  
Ability: Rock Head  
Shiny: Yes  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Double-Edge  
- Aqua Jet  
- Head Smash
- Crunch

Another new one I found. It made the form Red-Stripped and gave ability Reckless.

**Comment by Pierrounator** [comment]
`Basculin-Blue` instead of `Basculin-Blue-Striped` and it works ;)
Because the form in PKHeX is called `Blue` and not `Blue-Striped`

**Comment by architdate** [comment]
The issue with manaphy shiny legality is that the event is actually an egg which needs to be hatched to make it shiny. However I can look into the rest of the issues. Thanks for reporting. @Pierrounator is correct about the Basculin issue too, I think that should be fixed in the base PKHeX itself

**Comment by architdate** [comment]
I have submitted a PR to fix the Basculin issue in the base PKHeX code. Once that fix is applied by Kaphotics, the import will work fine.

**Comment by DJPanda065** [comment]
Blissey (F) @ Leftovers
Ability: Natural Cure
EVs: 252 HP / 252 Def / 4 SpD
Bold Nature
IVs: 0 Atk
- Sweet Scent
- Wish
- Protect
- Toxic

This one is another one that I can't seem to get fully legal. I get PID nature and encounter mismatches. As for the moves they seem fine to me.

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/30076424-551c8de8-92ab-11e7-8569-d819f06957ba.png)
the reason why wish chansey doesnt work is because it needs to be hatched from an event egg. Since an egg is not a pokemon it isnt validated by my autolegality yet.

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/30076587-f0936e72-92ab-11e7-85f2-d88ac6c7ee14.png)
shiny manaphy also has the same issue

**Comment by architdate** [comment]
The zapdos issue is because PIDIV generations are fixed on hardcoded IV's as of now, which means that hidden powers are compromised. However I am planning on coding in a hidden power PIDIV autolegality soon. However for now, I seemed to have addressed every bug here, so closing this issue for now. Feel free to open a feature request of Hidden Powers + Gen3/4 legal PID generation
