### ISSUE TITLE
[Request] Set Language/Country/Subregion in trainerdata.txt

### ISSUE THREAD

**Issue by Pierrounator** [architdate/PKHeX-Auto-Legality-Mod#11]
I don't know if it's possible, but I suggest to add the posibility to add the language/country/subregion in the trainerdata.txt to gen pokemon in our own language.

TID:12345
SID:54321
OT:PKHeX
Gender:F
Lang:Fr
Country:France
Region:Auvergne

But there's a bug in PKHeX on regions, if you put the game in english for example some french region have an english name...

**Comment by architdate** [comment]
Already an open issue, please continue in #6
