### ISSUE TITLE
Little Cup Sets issues

### ISSUE THREAD

**Issue by ReZeroEmiria** [architdate/PKHeX-Auto-Legality-Mod#13]
Having some problems with importing Little cup sets. Bulbasaur and Charmander don't work from smogon.

Charmander @ Choice Scarf
Level: 5
Ability: Solar Power
EVs: 44 HP / 12 Def / 200 SpA / 236 Spe
Modest Nature
- Fire Blast
- Hidden Power Grass
- Ancient Power
- Dragon Pulse

This set should work easily, it's just egg moves and some IV changes for HP Grass. Bulbasaur's is a celebrate bulbasaur so I feel like that would be a problem. WIll continue testing little cup sets.

**Comment by Pierrounator** [comment]
It's due to the automatic hypertrain fonctionality.
I mean, the mod tries to hypertrain the IV everytime. And you can't hypertrain a pokemon under lvl100. That's why you have the error. If you remove `level: 5` and you gen it and then you put lvl5 manually with non-hypertrained IV in PKHeX it's legal.

~~Gosh, my english sucks~~

**Comment by architdate** [comment]
yeah the mod probably fails because of this. I'll fix this issue in around 6 hours when I am free

**Comment by architdate** [comment]
The latest commit of PKHeX with my mod works with this. This issue was because PKHeX base started automatically hypertraining every pokemon regardless of the level. However its been fixed in a recent commit. Try using the latest commit of my mod and the latest commit of PKHeX @ReZeroEmiria

**Comment by ReZeroEmiria** [comment]
Just wanted to be more specific with the Bulbasaur issue so I took screenshots.

I tried to do this set

Bulbasaur @ Normalium Z
Ability: Chlorophyll
EVs: 52 Def / 160 SpA / 240 Spe
Modest Nature
- Celebrate
- Sludge Bomb
- Giga Drain
- Hidden Power Fire

I took off the level 5 so that there was no level/hyptraining issue (this was the problem with charmander)
![1](https://user-images.githubusercontent.com/31756219/30232601-eb59b776-94be-11e7-80c8-08b773fb7881.png)
![2](https://user-images.githubusercontent.com/31756219/30232600-eb56c700-94be-11e7-9356-2496c4c7b900.png)
![3](https://user-images.githubusercontent.com/31756219/30232603-eb5d63c6-94be-11e7-8afd-2dc7d7942c77.png)
![4](https://user-images.githubusercontent.com/31756219/30232602-eb5bcf98-94be-11e7-92cf-b18cfe1b733a.png)
![5](https://user-images.githubusercontent.com/31756219/30232604-eb656d28-94be-11e7-93cc-9c774db0d51c.png)

For him, I think maybe the issue is the Celebrate move?
I tried to import an XY set of LC Bulbasaur

Bulbasaur @ Life Orb
Ability: Chlorophyll
EVs: 240 SpA / 240 Spe
IVs: 0 HP
Modest Nature
- Sludge Bomb
- Solar Beam
- Sleep Powder
- Hidden Power Fire

Again, I removed the level 5, and this happened. 
The IVs got reworked to be HP Fire and the specified 0 IV in HP was replaced.

![11](https://user-images.githubusercontent.com/31756219/30232657-37d3c966-94bf-11e7-870d-3a28d81d1eeb.png)

![12](https://user-images.githubusercontent.com/31756219/30232690-635b2ba6-94bf-11e7-8798-e620fface774.png)

Lastly, not sure if it's been brought up but here the Bulbasaur is legit but the date for egg met is 1/1/2000, I also imported another pokemon and the date stayed the same, wouldn't it look better if the Egg Met Conditions' date was the same as the Met Date?

**Comment by architdate** [comment]
It would definitely look better, I just coded the bare minimum for now haha. The mod as of now is still pretty Beta. The issue with the level 5's is because of PKHeX (kwsch's) code itself. The latest commit has fixed the Hypertraining at level 5 which was causing this issue 👍
