### ISSUE TITLE
Genesect from Mewtwo Awakens Movie

### ISSUE THREAD

**Issue by optizard** [architdate/PKHeX-Auto-Legality-Mod#14]
Importing the Genesect without the Douse Drive (and I think even the other drives) and without the "Shiny: Yes" will generate a legal Shiny one. But trying to import the set right below there will make PKHeX flag everything as illegal. I think that the problem might be connected to the fact that Genesect changes to Douse Form with the Dousing Drive. Maybe it is related to the Mega/Primal Form import error. I didn't figure out however why shininess in the imported set make it illegal  

**LEGALITY ISSUE SET**
Genesect @ Douse Drive
Ability: Download
Shiny: Yes
EVs: 252 Atk / 4 SpD / 252 Spe
Hasty Nature
- Shift Gear
- Blaze Kick
- Extreme Speed
- Iron Head

**LEGAL ONE**
Genesect
Ability: Download
EVs: 252 Atk / 4 SpD / 252 Spe
Hasty Nature
- Shift Gear
- Blaze Kick
- Extreme Speed
- Iron Head

![cattura13](https://user-images.githubusercontent.com/31184488/30241525-5403f00e-9585-11e7-9072-845c9d078a12.png)

**Comment by architdate** [comment]
Only the shiny one is fixed. Genesect douse will still have to use the douse form
