### ISSUE TITLE
[Bug] Mod is not working with a Gen6 save.

### ISSUE THREAD

**Issue by Pierrounator** [architdate/PKHeX-Auto-Legality-Mod#15]
The set I tried:

```
Bronzor @ Berry Juice
Level: 50
Ability: Levitate
EVs: 60 HP / 4 Atk / 228 Def / 4 SpA / 148 SpD / 12 Spe
Careful Nature
- Stealth Rock
- Recycle
- Earthquake
- Psychic
```

The error I get:

https://gyazo.com/485b15b62b6a49433f98c76afba9a5cc

When I click on **[Continue]**

https://gyazo.com/1cb3d5c11ecf8245687f58deca2d90ad

I tried with many differents sets, I always got this error with a **X save**

**Comment by architdate** [comment]
Adding previous generation support as a feature request.
