### ISSUE TITLE
Having Trouble Making Celebi Auto Mod Long Wait

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#18]
Hey there! The auto mod is having trouble getting the Celebi working. I have a full mgdb and gen 4 is 4th out of 7th on the priority scanning for it. Yet it took about 10 mins for the auto mod to get legal. Below is the set.

Celebi @ Leftovers
Ability: Natural Cure
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
- Nasty Plot
- Giga Drain
- Psychic
- Hidden Power [Fire]

If you have any solutions or anything just let me know! -DJ/JGamez

**Comment by DJPanda065** [comment]
This one in different.

It's a HGSS Mewtwo that auto mod couldn't manage to make shiny.

Mewtwo @ Mewtwonite X  
Ability: Pressure  
Shiny: Yes  
EVs: 252 Atk / 4 SpA / 252 Spe  
Hasty Nature  
- Low Kick  
- Taunt  
- Ice Beam  
- Zen Headbutt

**Comment by LemonatedCat** [comment]
As far as i know you can set the Priorities if needed.

**Comment by architdate** [comment]
@DJPanda065 Added a tertiary shiny check in my code. Commiting soon
