### ISSUE TITLE
Gen 1 Mon Set Auto Fail

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#21]
OnionRing (Nidoking) @ Life Orb
Ability: Sheer Force
EVs: 4 Atk / 252 SpA / 252 Spe
Naive Nature
IVs: 0 Atk
- Blizzard
- Sludge Wave
- Fissure
- Protect

Hey so I tried doing this set and auto mod couldn't figured it out. I made it manually, its a gen 1 Nidoking. Because of Fissure.

**Comment by architdate** [comment]
Im fairly aware of this issue, and have a plan to fix it, but it would be done much more efficiently when the base PKHeX is updated to support USUM games
