### ISSUE TITLE
Power Construct Zyguarde changed to have Aura Break

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#22]
Hey so I tried making this and it gave me Aura Break instead. (With the 50% form and not 50%C which has the Power Construct ability. Switching the thing to 50%C kept it legal and gave it power construct.

Latest commit of auto mod and fairly recent pkhex base from 5 days ago.

Zygarde @ Leftovers
Ability: Power Construct
EVs: 252 HP / 4 Atk / 252 Def
Impish Nature
- Thousand Arrows
- Rest
- Glare
- Sleep Talk

**Comment by architdate** [comment]
Seems like an issue in the base PKHeX itself. I'll send a PR to resolve this, will keep this issue open for the time being

**Comment by architdate** [comment]
Update to latest base PKHeX to solve this issue
