### ISSUE TITLE
Gen 3 Wish/Misc event fixing (Adding M-2 RNG)

### ISSUE THREAD

**Issue by Pierrounator** [architdate/PKHeX-Auto-Legality-Mod#24]
```
Boom! (Oddish) (M) @ Eviolite
Ability: Chlorophyll
Shiny: Yes
EVs: 252 HP / 128 Def / 128 SpD
Timid Nature
IVs: 0 Atk
- Moonblast
- Infestation
- Leech Seed
- Protect
```

This pokemon is not genned correctly on PKHeX. Maybe because of the event. If you need more informations, feel free to ask :)

**Comment by architdate** [comment]
Yes! Leech seed oddish isn't supported yet cuz of gen 3 events using a different algorithm. I plan to fix these events soon, however they are not priority right now. The main priority atm is getting Gen 2 VC moves to work

**Comment by kamronbatman** [comment]
PKhex determines gen 3 events heuristically using an internal table. It shouldn't be difficult to convert the legality checks into a generation algorithm. The legality of course will only be as accurate as PKHex, which unfortunately isn't saying much.  There are still several unknowns which prevent making blanket gen 3 events.

As for the wondercard based events (WC3 eggs), those should be fairly straightforward and _safe_ to create.

**Comment by architdate** [comment]
Re coded event handling. Gen 3 events will soon be coded by using @kamronbatman 's solution! Thanks
