### ISSUE TITLE
[Feature Request] Gender, Country, Sub-region and 3DS Region to be Automatically Filled alongside TID, SID and OT  

### ISSUE THREAD

**Issue by cainan-c** [architdate/PKHeX-Auto-Legality-Mod#28]
So I asked you this over discord and you said to open it as a feature request on Github **So here it is**
That aside this would be useful for 1) People who are Female in game 2) People who want it their Country/ 3DS Region to be theirs, etc.

**Comment by Pierrounator** [comment]
Already asked 4 months ago but yes it would be awesome

**Comment by architdate** [comment]
Gender done

**Comment by architdate** [comment]
Country and 3DS region will most likely be done in a few days

**Comment by cainan-c** [comment]
Heh, nice. Thanks for all the work you have done!
