### ISSUE TITLE
Gen 2 Legality Checking

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#29]
Ho-Oh @ Leftovers
EVs: 252 HP / 204 Def / 52 SpD
Ability: Regenerator
Level: 100
Shiny: Yes
Impish Nature
- Sacred Fire
- Toxic
- Recover
- Brave Bird

Lugia @ Leftovers
Shiny: Yes
Ability: Multiscale
EVs: 252 HP / 160 Def / 96 Spe
Bold Nature
- Toxic
- Roost
- Whirlwind
- Substitute

Hey so I tried doing these. They can be legal, I will also give you a file samples. Auto mod can't seem to figure it out, same deal with shiny Deoxys.

Deoxys-Attack
EVs: 252 Atk / 4 SpD / 252 Spe
Ability: Pressure
Level: 100
Shiny: Yes
Jolly Nature
- Drain Punch
- Calm Mind
- Recover
- Poison Jab

[Shiny Lugia, Deoxys, and Ho-oh.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1564973/Shiny.Lugia.Deoxys.and.Ho-oh.zip)

**Comment by architdate** [comment]
@DJPanda065 oh, thanks for letting me know. I think i know what is causing this
