### ISSUE TITLE
Auto OT Magearna

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#31]
Hey so its a really small issue but whenever I use auto mod for Magearna it gives it a PKHeX OT vs the thing I have in my trainerdata.txt . When I select Magearna in mgdb then it gives my OT data.

This happens for every Magerna set I've done. Test the set below. Thanks!

Magearna @ Garchompite
IVs: 0 Atk / 0 Spe
EVs: 252 HP / 252 SpA / 4 SpD
Ability: Soul-Heart
Level: 100
Quiet Nature
- Trick Room
- Flash Cannon
- Focus Blast
- Thunderbolt

**Comment by DJPanda065** [comment]
Also maybe having auto mod created mons have the date on the computer rather than in 1/1/2000 or 6/29/17

**Comment by architdate** [comment]
The Magearna issue is something that is very tedious to solve gracefully. A lot of the events are OT locked, so doing a check would need me to check if the WCX is OT locked or not. Some of the Wondercard classes may not even have that boolean to check against. 

However, I will implement the date of static encounters and egg based Pokemon, as today's date. 
The Magearna issue will be solved if I can find proper documentation on OT locks for all implemented wonder card extensions.
