### ISSUE TITLE
Shiny Tri Attack Togekiss Auto Mod Fail

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#33]
Hey so I was doing the Togekiss set below and auto mod couldn't create it. Tri Attack was being flagged. So instead I did the Togetic set below and auto mod could do it. Then I simply evolved the Togetic and gave it Air Slash. (Tri Attack Togetic is Colosseum.)

Togekiss (F) @ Assault Vest  
Ability: Serene Grace  
Shiny: Yes  
EVs: 96 HP / 160 Def / 252 SpA  
Modest Nature  
- Air Slash  
- Zen Headbutt  
- Tri Attack  
- Dazzling Gleam 

Togetic (M) @ Assault Vest
IVs: 19 HP / 3 Atk / 7 Def / 7 SpA / 3 SpD / 19 Spe
EVs: 96 HP / 160 Def / 252 SpA
Ability: Serene Grace
Level: 100
Shiny: Yes
Modest Nature
- Tri Attack
- Zen Headbutt
- Dazzling Gleam

[6IV Shiny Tri Attack Modest Togekiss.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1594692/6IV.Shiny.Tri.Attack.Modest.Togekiss.zip)

**Comment by architdate** [comment]
Closed in commit `120ce73`
