### ISSUE TITLE
Legal Shiny Shedinja with Sword Dance and Sucker Punch

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#36]
this a Legal Shiny Shedinja with Sword Dance and Sucker Punch

![shedinja1](https://user-images.githubusercontent.com/18640392/34520885-51e14bd0-f0a4-11e7-824e-ca73029b14f8.jpg)

![shedinja 2](https://user-images.githubusercontent.com/18640392/34521061-2ecb6ae4-f0a5-11e7-80b9-5c406b7f3b26.jpg)

![shedinja 3](https://user-images.githubusercontent.com/18640392/34521072-3509595c-f0a5-11e7-9308-4fb56e39aed2.jpg)

[Legal Shiny Shedinija.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1600340/Legal.Shiny.Shedinija.zip)

**Comment by architdate** [comment]
Issue here is: Does not gen it as a shiny
