### ISSUE TITLE
Oricorio-Pom-Pom set Unable to have Correct Form

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#38]
Oricorio-Pom-Pom (F) @ Focus Sash
IVs: 30 Atk / 30 Def
EVs: 252 SpA / 252 Spe
Ability: Dancer
Level: 100
Timid Nature
- Air Slash
- Revelation Dance
- Hidden Power [Ice]
- Protect

For some reason whenever I try to do this set it turns the mon into its Balie form.

**Comment by architdate** [comment]
This is an issue with base pkhex, standard imports (without auto legality) will also lead to the same issue. Issue should be opened in the main repo
