### ISSUE TITLE
Poke Bank XY/ORAS Regirock and Registeel does not work on Import with Auto-Legality Mod

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#39]
![pokebank xyoras regirock](https://user-images.githubusercontent.com/18640392/34637683-d76a0a6c-f2d4-11e7-9a51-fc90f53ad6cd.jpg)

![pokebank xyoras registeel](https://user-images.githubusercontent.com/18640392/34637685-e143da36-f2d4-11e7-90ab-7bedc4033906.jpg)

[Poke Bank XYORAS Regirock and Registeel .zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1608551/Poke.Bank.XYORAS.Regirock.and.Registeel.zip)

Registeel @ Leftovers
EVs: 252 HP / 100 Atk / 158 Spe
Ability: Light Metal
Level: 100
Adamant Nature
- Iron Head
- Rest
- Psych Up
- Earthquake

Regirock @ Leftovers
EVs: 252 HP / 100 Atk / 158 Spe
Ability: Sturdy
Level: 100
Adamant Nature
- Iron Head
- Rest
- Psych Up
- Earthquake

**Comment by architdate** [comment]
`.plx` support isn't yet included in PKHeX. The regis mentioned are events in the format of `.pl6` until PKHeX supports `.plx` reading, this issue cannot be resolved

**Comment by kwsch** [comment]
pl6 data is just used for importing data to the save file; the legality data is watered down into a manually defined structure.

these encounters are saved as EncounterLink IEncounterable data.

**Comment by architdate** [comment]
@kwsch yup! So the way I did it was I wrote a function to convert PL6_PKM into a PKM (similar to the ConvertToPKM function for wondercards.) Since the structure closely resembles the WC6 structure, I was able to get a PKM that could be further legalized based on standard PL constants like FE = false etc :)
