### ISSUE TITLE
How to use QR Rental Team Code Mod?

### ISSUE THREAD

**Issue by ricksee** [architdate/PKHeX-Auto-Legality-Mod#40]
How is it to use the QR Rental Team Code Mod. For the program it only shows me the option to Export QR Code so are there instructions to use it?

**Comment by architdate** [comment]
1) Login to your Pokemon Global Link account at https://3ds.pokemon-gl.com
2) Visit this website: https://3ds.pokemon-gl.com/rentalteam/usum
3) Find any team you would like from the QR Rental teams others have posted
4) Click on the team to open it and click on Reveal QR Code
5) Right click and copy the QR code image
6) Click the Export QR Code option on my mod
7) It will gen all 6 of the Pokemon and it will also copy the showdown team of the QR code to your clipboard

**Comment by ricksee** [comment]
Thank you. Does the QR code have to be in the same holder as the program?
 Oh wait sorry I only have to copy the QR code, thanks.
