### ISSUE TITLE
Wish Jirachi Auto Mod Fail

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#43]
Jirachi @ Leftovers
Ability: Serene Grace
EVs: 252 HP / 4 Def / 252 SpD
Careful Nature
- Stealth Rock
- Iron Head
- Body Slam
- Wish

[Careful Gen 3 Wish Jirachi.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1613550/Careful.Gen.3.Wish.Jirachi.zip)

Even in my mgdb it still can't seem to make this. Not sure if possible to fix on your end.

**Comment by architdate** [comment]
It is possible to fix, it's just gonna be very tedious. This is a tanbatta gen 3 jirachi event whose rng I have not yet implemented
