### ISSUE TITLE
Shiny Gen 3 Groudon

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#44]
This was a request I got. In my opinion as long as stuff like hidden powers and stuff is encounted for gen 3 rng doesn't have to be top of the line thanks to hyper training. Credits to Oxadis for getting this for me

Groudon @ Red Orb
Ability: Drought
Shiny: Yes
EVs: 252 HP / 252 Atk / 4 SpA
Naughty Nature
- Body Slam
- Brick Break
- Focus Blast
- Eruption 

[383_-_Groudon_-_65F752880D44.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1616899/383_-_Groudon_-_65F752880D44.zip)

**Comment by architdate** [comment]
What is the issue here? The set gens perfectly for me. It also maintains the hidden power based on the IVs specified
