### ISSUE TITLE
Banette Cotton Guard Fail

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#46]
Banette (F) @ Banettite
Ability: Cursed Body
EVs: 248 HP / 8 Atk / 252 SpD
Careful Nature
- Cotton Guard
- Sucker Punch
- Taunt
- Protect

Auto-Mod can't seem to make this. Entree Forest Cotton Guard
[354 - Banette - C44290502667.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1633529/354.-.Banette.-.C44290502667.zip)

**Comment by architdate** [comment]
creating a new file may be unavoidable.

I was planning on leveraging the static encounters listed. However they are internal static classes to PKHeX Core, and for that a file will have to be created in PKHeX.Core or duplicate code for earlier encounters would have to be copied over from the core project. Both of which im not too keen to do
