### ISSUE TITLE
Keldeo-Resolute Broken in the Auto import

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#47]
Keldeo-Resolute @ Life Orb
Ability: Justified
EVs: 4 HP / 252 SpA / 252 Spe
Modest Nature
- Aqua Jet
- Hydro Pump
- Icy Wind
- Secret Sword

![image](https://user-images.githubusercontent.com/18640392/35183058-32808bea-fdf9-11e7-83c3-4efe1e4881c2.png)

**Comment by architdate** [comment]
Make sure the latest `mgdb` is in the same directory as your PKHeX. mgdb can be found [here](https://github.com/projectpokemon/EventsGallery)
