### ISSUE TITLE
Togepi Gift in HGSS and the Move: Extrasensory it shows illegal 

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#48]
Move: Extrasensory it shows illegal and in legal in HGSS
![image](https://user-images.githubusercontent.com/18640392/35191629-4e41f3be-fe99-11e7-9d16-26d87e369416.png)

this Togepi HGSS Gift
![hgss togepi gift](https://user-images.githubusercontent.com/18640392/35191635-674602a6-fe99-11e7-8ef2-49a4c26f1cf8.jpg)

https://www.serebii.net/heartgoldsoulsilver/gift.shtml

[175 - Togepi - C7A97942EF72.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1649565/175.-.Togepi.-.C7A97942EF72.zip)

and i test the auto mod and it goes to Crystal and the move is Extrasensory in GSC not 

this GS Togepi Gift 
![gs togepi gift](https://user-images.githubusercontent.com/18640392/35191654-eedc0d1e-fe99-11e7-9e0c-501a5937c5fc.jpg)

https://www.serebii.net/gs/gift.shtml

**Comment by Orionsilver** [comment]
check this issue in the base PKHeX issue
https://github.com/kwsch/PKHeX/issues/1766

**Comment by Orionsilver** [comment]
i change to togepi to togekiss and it show to Crystal

![image](https://user-images.githubusercontent.com/18640392/35191853-f9531b3e-fe9e-11e7-9f42-fa0b97dc77cd.png)

[468 ★ - Togekiss - BDB718348E02.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1649592/468.-.Togekiss.-.BDB718348E02.zip)

**Comment by architdate** [comment]
Referenced issue needs to be resolved first in base PKHeX before implementing any fix (if even necessary)

**Comment by architdate** [comment]
Issue reopened since this isn't fixed yet

**Comment by architdate** [comment]
Fixed in [e37fdc6](https://github.com/architdate/PKHeX-Auto-Legality-Mod/commit/e37fdc670e410cecb40a2c30694c89211e5f6d4b)
