### ISSUE TITLE
Body Slam Tauros + Wish Heal Bell Lickitung

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#51]
Part of a gen request I was doing. Credits for Ice Atom/Spooky Vampire for making me the file.

Tauros (M) @ Life Orb
EVs: 252 Atk / 4 SpA / 252 Spe
Ability: Anger Point
Level: 100
Shiny: Yes
Naive Nature
- Body Slam
- Earthquake
- Fire Blast
- Zen Headbutt

Keeps giving encounter move (for body slam) and pid encounter.
[128 ★ - Tauros - D2F85A48D694.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1670448/128.-.Tauros.-.D2F85A48D694.zip)

**Comment by DJPanda065** [comment]
I can understand the mod not able to do PID stuff. But maybe have it be able to make it legal with the nature and moves would be nice. :)

Lickitung @ Eviolite 
Ability: Oblivious 
EVs: 196 HP / 76 Def / 236 SpD 
Impish Nature 
- Wish 
- Protect 
- Heal Bell 
- Knock Off 

[Wish Heal Bell Lickitung Impish.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1670479/Wish.Heal.Bell.Lickitung.Impish.zip)

**Comment by architdate** [comment]
invalid. Fixed in the latest commit
