### ISSUE TITLE
Manaphy Test SID is set to 0 it is a SID Issue

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#53]
i did a test on DJ Panda Manaphy Set 

Manaphy @ Leftovers
Ability: Hydration
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Tail Glow
- Psychic
- Rain Dance
- Surf

![image](https://user-images.githubusercontent.com/18640392/35754284-5cb239da-087c-11e8-97c8-d4915bf96e77.png)

[490 - Manaphy - 9119DB22D856.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1690796/490.-.Manaphy.-.9119DB22D856.zip)

SID issue

**Comment by architdate** [comment]
Irrelevant. SID is the lowest priority for legality checks right now. Main priority is to make the pokemon legal which it does.
