### ISSUE TITLE
Gen 6 Auto Mod Gen 3 Legality

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#59]
Hey so apparently auto mod (gen 6) struggles with doing earlier origin games. So far everything else works well.

Clefable (M) @ Leftovers
Ability: Magic Guard
Shiny: Yes
EVs: 252 HP / 172 Def / 84 SpD
Calm Nature
- Stealth Rock
- Moonblast
- Soft-Boiled
- Thunder Wave

[036 ★ - Clefable - 691206887DE4.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1705650/036.-.Clefable.-.691206887DE4.zip)

**Comment by architdate** [comment]
Preliminary fix would be up soon, but it will most likely still cause some issues. Permanent fix will be when I find the exact cause of this issue
