### ISSUE TITLE
[Feature Request] Additions for trainerdata.txt

### ISSUE THREAD

**Issue by rmcqu1** [architdate/PKHeX-Auto-Legality-Mod#6]
Could add the ability to change the default 3ds location?

**Comment by Pierrounator** [comment]
It would be great to be able to put multiple Trainer information.

I mean 1 trainer / Game like:

```
Save:X
TID:12345
SID:54321
OT:PKHeX
Gender:F
Language:French
Country:France
Subregion:Auvergne

Save:Moon
TID:56789
SID:98765
OT:Moon
Gender:M
Language:French
Country:France
Subregion:Auvergne
```

In that way, when we open X save or Moon save it will take the right informations.

**Edit:** Nvm, because it's not supported for older generation. But it still can be great for Sun and Moon 😋

**Comment by architdate** [comment]
Updated issue existing. Taking the discussion there
