### ISSUE TITLE
Auto Legality ORAS Improvements

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#60]
So just trying to export old mons as showdown and reimport them with auto mod kinda is impossible for auto mod to fix/make some of these. Here are some sets and maybe trying out a bunch of the mons in my save. (Note they are illegal but can be legal normally through pkhex. This was during the power saves era and stuff.)

Deoxys-Defense
EVs: 6 HP / 252 SpA / 252 Spe
Ability: Pressure
Level: 100
Shiny: Yes
Timid Nature
- Psycho Boost
- Focus Blast
- Grass Knot
- Flash Cannon

Vivillon-Modern (M)
EVs: 6 HP / 252 SpA / 252 Spe
Ability: Compound Eyes
Level: 100
Shiny: Yes
Modest Nature
- Quiver Dance
- Sleep Powder
- Bug Buzz
- Hurricane

Feraligatr (M)
EVs: 252 Atk / 6 SpD / 252 Spe
Ability: Torrent
Level: 100
Adamant Nature
- Crunch
- Waterfall
- Ice Punch
- Dragon Dance

[main [Jared (Y) - 203207131306].zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1709702/main.Jared.Y.-.203207131306.zip)

**Comment by architdate** [comment]
Like I said, the full legality of this is still WIP, I'm aware of these issues already. Closing now since this is already in development :)
