### ISSUE TITLE
Shiny Celebi Broken from Latest PKHeX Commit

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#61]
Celebi @ Leftovers
IVs: 30 Spe
EVs: 252 HP / 220 Def / 36 Spe
Ability: Natural Cure
Level: 100
Shiny: Yes
Bold Nature
- Calm Mind
- Recover
- Psychic
- Hidden Power [Ice]

Auto mod can't seem to do this anymore. The regular pkhex can if a legal file of gen 2 celebi is selected.

[251 ★ - Celebi - 45E70036F843.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1713500/251.-.Celebi.-.45E70036F843.zip)

[Auto PKHeX 4341.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1713501/Auto.PKHeX.4341.zip)

**Comment by architdate** [comment]
Cant replicate on my end.
![image](https://user-images.githubusercontent.com/17220860/36069059-5c3f7a1a-0f1d-11e8-8eee-0687b65fc4fb.png)

**Comment by architdate** [comment]
New base PKHeX commit breaks this
