### ISSUE TITLE
Shiny Partner Cap Pika Auto Mod Error

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#64]
Pikachu-Partner (M) @ Pikashunium Z
IVs: 0 Atk / 30 Def
EVs: 252 SpA / 4 SpD / 252 Spe
Ability: Static
Level: 100
Shiny: Yes
Hardy Nature
- Thunderbolt
- Signal Beam
- Hidden Power [Ice]
- Grass Knot

[025-07 ★ - Pikachu - 993A045A649A.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/1734995/025-07.-.Pikachu.-.993A045A649A.zip)

Auto mod struggles to do this.

**Comment by architdate** [comment]
Not an automod issue. PKHeX does not allow this even with mgdb. It was removed by kaphotics inh a previous commit
