### ISSUE TITLE
Somebody please help me

### ISSUE THREAD

**Issue by Looply2323** [architdate/PKHeX-Auto-Legality-Mod#72]
![error](https://user-images.githubusercontent.com/38604115/39092620-dc071290-4644-11e8-91a8-a305f4b656b3.png)
![error2](https://user-images.githubusercontent.com/38604115/39092621-dc359cf0-4644-11e8-91ee-768349cb6021.png)

**Comment by chenzw95** [comment]
This is not a support forum. Please refer to our Discord server.
