### ISSUE TITLE
Gen 6 Auto Legality Defog Giritina

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#73]
Giratina-Origin @ Griseous Orb
Ability: Levitate
EVs: 252 Def / 244 SpA / 12 Spe
Modest Nature
- Hex
- Draco Meteor
- Thunder Wave
- Defog

Can't seem to make this. Since its Defog in Gen 6 there is no tutor. Has to come from gen 4.

**Comment by architdate** [comment]
Self Reference: Encounter Type does not match Encounter error must be fixed
