### ISSUE TITLE
[Request] Specify Pokeball

### ISSUE THREAD

**Issue by Pierrounator** [architdate/PKHeX-Auto-Legality-Mod#8]
It would be great to specify the pokeball.

For example: 
_I don't know if this set it legal with this ball btw_

Chansey @ Eviolite  
Ability: Natural Cure  
EVs: 4 HP / 252 Def / 252 SpD  
Bold Nature  
**Ball: Friend Ball**
Thunder Wave
Soft-Boiled  
Seismic Toss  
Stealth Rock

**Comment by Spindlyskit** [comment]
you can easily change the ball after the import so I don't see the point in this

**Comment by Pierrounator** [comment]
I often get error when I try to put someballs because it's only from Gen2, Gen3, ...

So, with this feature, the pokemon would be from the good generation to have this ball.

**Comment by architdate** [comment]
On further consideration this would be probably more feasible in trainerdata.txt as preferred pokeball since there is no real way in which showdown sets allow mention of a pokeball. There is no point if you have to manually edit the set to specify the pokeball

**Comment by architdate** [comment]
Can be further continued in trainerdata.txt related issues
