### ISSUE TITLE
Blastoise (Squirtle Event) is issue on import automod 

### ISSUE THREAD

**Issue by Orionsilver** [architdate/PKHeX-Auto-Legality-Mod#81]
Blastoise @ Rocky Helmet  
Ability: Torrent  
EVs: 252 HP / 64 Def / 44 SpA / 148 SpD  
Bold Nature  
IVs: 0 Atk  
- Water Spout  
- Aura Sphere  
- Protect  
- Follow Me

it is from Black/white 2 event and it red triangle with Pokemon Y

[009 - Blastoise - 33371DE6C33A.zip](https://github.com/architdate/PKHeX-Auto-Legality-Mod/files/2069558/009.-.Blastoise.-.33371DE6C33A.zip)

**Comment by Orionsilver** [comment]
i'm using the latest Automod

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/40935208-ed1dee54-6869-11e8-95ec-0791771e9494.png)
Invalid set
